# Copyright 2024, UNSW
#
# SPDX-License-Identifier: BSD-2-Clause

name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-24.05
      - name: Build docs site
        run: nix-shell --run './build.sh'
      - name: Upload built site
        uses: actions/upload-artifact@v4
        with:
          name: lionsos_docs
          path: public
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    # Do not deploy unless we've pushed to main and we're not on a fork
    if: ${{ github.repository_owner == 'au-ts' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: lionsos_docs
          path: lionsos_docs
      - name: Setup SSH key
        run: ./ci/setup_ssh_key.sh
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      - name: Deploy
        run: |
          cat ./ci/sftp | sftp -i ~/.ssh/id_ed25519 -J ts lions_web_updater@lions-www.keg.cse.unsw.edu.au
